Not Found: /admin/config.html
Not Found: /admin/config/1
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Not Found: /admin/config.html
Not Found: /admin/config/{% static https://code.jquery.com/jquery-2.2.4.min.js
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
<<<<<<< HEAD
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Not Found: /admin/config.html
Not Found: /admin/config/itens.html
Internal Server Error: /admin/home
Traceback (most recent call last):
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/coapp_system/admin_cohabitat/views/home.py", line 9, in home
    profile = Profile.objects.get(user=request.user.id)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/c/Users/humbe/Desktop/LDSProjs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Profile matching query does not exist.
Not Found: /admin/config/recursos.html
Not Found: /admin/config/planos.html
Not Found: /admin/config/menu.html
Not Found: /admin/config/recursos.html
Not Found: /admin/config/recursos.html
Not Found: /admin/config.html
Not Found: /admin/config.html
Not Found: /admin/config.html
Not Found: /admin/config/config.html
=======
  File "/home/lds/ldsprojs/coapp_system/admin_cohabitat/views/config.py", line 15, in config
    'config.html', data
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '['coworking_info'].name' from 'data['coworking_info'].name'
Not Found: /home/lds/ldsprojs/coapp_system/coapp_system/static/media/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/staticimages/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /api/v1/coworkings/2
Not Found: /api/v1/coworkings/3
Not Found: /api/v1/coworkings/2
Not Found: /api/v1/coworkings/3
Not Found: /api/v1/coworkings/2/contact_infos
Not Found: /api/v1/coworkings/30/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/8
Not Found: /api/v1/coworkings/2
Not Found: /api/v1/coworkings/3
Not Found: /api/v1/coworkings/2/contact_infos
Not Found: /api/v1/coworkings/24/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/8
Not Found: /api/v1/coworkings/30/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/11
Not Found: /api/v1/coworkings/2/contact_infos/16
Not Found: /api/v1/coworkings/37/contact_infos/2
Not Found: /api/v1/coworkings/2
Not Found: /api/v1/coworkings/3
Not Found: /api/v1/coworkings/2/contact_infos
Not Found: /api/v1/coworkings/24/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/8
Not Found: /api/v1/coworkings/29/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/11
Not Found: /api/v1/coworkings/2/contact_infos/16
Not Found: /api/v1/coworkings/36/contact_infos/2
Not Found: /api/v1/coworkings/2
Not Found: /api/v1/coworkings/3
Not Found: /api/v1/coworkings/2/contact_infos
Not Found: /api/v1/coworkings/24/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/8
Not Found: /api/v1/coworkings/2/contact_infos
Not Found: /api/v1/coworkings/29/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/15
Not Found: /api/v1/coworkings/2/contact_infos/20
Not Found: /api/v1/coworkings/36/contact_infos/2
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /api/v1/coworkings/2
Not Found: /api/v1/coworkings/3
Not Found: /api/v1/coworkings/2/contact_infos
Not Found: /api/v1/coworkings/24/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/8
Not Found: /api/v1/coworkings/2/contact_infos
Not Found: /api/v1/coworkings/29/contact_infos/2
Not Found: /api/v1/coworkings/2/contact_infos/15
Not Found: /api/v1/coworkings/2/contact_infos/20
Not Found: /api/v1/coworkings/36/contact_infos/2
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
Not Found: /admin/images/logos/Screenshot_20170912-092854.png
>>>>>>> 7a1eb1788b36c78e8c90a3b6aefcf73449126d1f
Internal Server Error: /admin/config/2
Traceback (most recent call last):
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lds/ldsprojs/coapp_system/admin_cohabitat/views/config.py", line 12, in config
    coworking = Coworking.objects.get(coworking_id)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 376, in get
    clone = self.filter(*args, **kwargs)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1130, in build_filter
    arg, value = filter_expr
ValueError: need more than 1 value to unpack
Internal Server Error: /admin/config/2
Traceback (most recent call last):
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/rest_framework/response.py", line 57, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
AssertionError: .accepted_renderer not set on Response
Internal Server Error: /admin/config/2
Traceback (most recent call last):
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/lds/ldsprojs/env/local/lib/python2.7/site-packages/rest_framework/response.py", line 57, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
AssertionError: .accepted_renderer not set on Response
Not Found: /admin/config/2
Not Found: /admin/config/2
Not Found: /admin/config/2
Not Found: /admin/config/recursos.html
Not Found: /admin/config/menu.html
Not Found: /admin/config.html
Not Found: /admin/config.html
Not Found: /media//media/images/profiles/write-593333_1920.jpg
Not Found: /media//media/images/profiles/write-593333_1920.jpg
Not Found: /admin/config.html
Not Found: /admin/config.html
Not Found: /admin/config/recursos.html
>>>>>>> 68cc4437f6e7bbc57a4f699d44799741c82da3f4
